In [3]:
import pandas as pd

In [7]:
parc_df = pd.read_csv("../../2020_NLP/parc/parc_features/parc_train_features.tsv", delimiter="\t", header=0)

In [8]:
parc_df.columns

Index(['Unnamed: 0', 'POS', 'dependency_head', 'dependency_label',
       'doc_token_number', 'lemma', 'ne_info', 'sentence_number',
       'sentence_token_number', 'token', 'cue_label', 'attribution',
       'token_-1', 'token_-2', 'token_-3', 'token_-4', 'token_-5', 'token_+1',
       'token_+2', 'token_+3', 'token_+4', 'token_+5', 'lemma_-1', 'lemma_-2',
       'lemma_-3', 'lemma_-4', 'lemma_-5', 'lemma_+1', 'lemma_+2', 'lemma_+3',
       'lemma_+4', 'lemma_+5', 'POS_-1', 'POS_-2', 'POS_-3', 'POS_-4',
       'POS_-5', 'POS_+1', 'POS_+2', 'POS_+3', 'POS_+4', 'POS_+5',
       'bigram_prev_token', 'bigram_prev_lemma', 'bigram_prev_POS',
       'bigram_following_token', 'bigram_following_lemma',
       'bigram_following_POS', 'shape', 'ne_short', 'relevant_ne', 'ne_+-5',
       'candidate_cue', 'reporting_verb', 'quotation', 'near_sent_boundary',
       'near_doc_boundary', 'dist_beg_sent', 'dist_end_sent', 'sent_len',
       'pn_in_sent', 'ne_in_sent', 'qm_in_sent', 'any_in_sent', 'quotation_pn',
       'quotation_ne', 'quotation_qm', 'filename', 'content_label_gold',
       'ancestor_is_cue', 'cue_in_window_of_5', 'distance_to_prev_cue',
       'distance_to_next_cue', 'cue_in_sentence'],
      dtype='object')

In [9]:
parc_df = parc_df[:200]

In [10]:
parc_df.head()

,Unnamed: 0,POS,dependency_head,dependency_label,doc_token_number,lemma,ne_info,sentence_number,sentence_token_number,token,...,quotation_pn,quotation_ne,quotation_qm,filename,content_label_gold,ancestor_is_cue,cue_in_window_of_5,distance_to_prev_cue,distance_to_next_cue,cue_in_sentence
0,0,NNP,9,nsubj,1,Pierre,B-PERSON,1,1,Pierre,...,O0,O1,O0,wsj_0001.tsv,O,0,0,.,.,0
1,1,NNP,1,flat,2,Vinken,E-PERSON,1,2,Vinken,...,O0,O1,O0,wsj_0001.tsv,O,0,0,.,.,0
2,2,",",1,punct,3,",",O,1,3,",",...,O0,O1,O0,wsj_0001.tsv,O,0,0,.,.,0
3,3,CD,5,nummod,4,61,B-DATE,1,4,61,...,O0,O1,O0,wsj_0001.tsv,O,0,0,.,.,0
4,4,NNS,6,obl:npmod,5,year,I-DATE,1,5,years,...,O0,O1,O0,wsj_0001.tsv,O,0,0,.,.,0

In [50]:
# Example output is a tuple of tuples as ((s1, s2), (c1, c2))

#Creating dummy input (Credits to Ellie)
list_of_tuples = list()

source1 = (0,1)
content1 = (7,14)
source2 = (50,53)
content2 = (55, 65)
source3 = (250, 250)
content3 = (255, 265)
source4 = (1340, 1342)
content4 = (1346, 1352)


tuple1 = (source1, content1)
tuple2 = (source2, content2)
tuple3 = (source3, content3)
tuple4 = (source4, content4)

list_of_tuples.append(tuple1)
list_of_tuples.append(tuple2)
list_of_tuples.append(tuple3)
list_of_tuples.append(tuple4)

print(list_of_tuples)

[((0, 1), (7, 14)), ((50, 53), (55, 65)), ((250, 250), (255, 265)), ((1340, 1342), (1346, 1352))]

Content features to attempt: content features about c itself
- is s mentioned in c? (check)
- are other speakers mentioned in it? ???
- how far is the content from the start of the paragraph? (sentence! check)
- length of words in c? (check and also for s)

In [92]:
def get_word_length(df, list_of_tuples, s_c): 
    """
    Get word length for the content or source in the tuple (specified by s or c)
    """
    assert s_c == 's' or s_c == 'c'
    
    for t in list_of_tuples:
        s_tuple, c_tuple = t
        if s_c == 'c':
            start, end = c_tuple
            df.loc[start:end, 'c_length'] = (end+1-start)
        if s_c == 's':
            start,end = s_tuple
            df.loc[start:end, 's_length'] = (end+1-start)

In [93]:
get_word_length(df, list_of_tuples, 'c')
get_word_length(df, list_of_tuples, 's')

In [94]:
df.head()

,POS,dependency_head,dependency_label,doc_token_number,lemma,ne_info,sentence_number,sentence_token_number,token,cue_label,...,filename,content_label_gold,ancestor_is_cue,cue_in_window_of_5,distance_to_prev_cue,distance_to_next_cue,cue_in_sentence,c_length,s_length,distance_c2sentstart
0,NNP,9,nsubj,1,Pierre,B-PERSON,1,1,Pierre,0,...,wsj_0001.tsv,O,0,0,.,.,0,NaN,2.0,NaN
1,NNP,1,flat,2,Vinken,E-PERSON,1,2,Vinken,0,...,wsj_0001.tsv,O,0,0,.,.,0,NaN,2.0,NaN
2,",",1,punct,3,",",O,1,3,",",0,...,wsj_0001.tsv,O,0,0,.,.,0,NaN,NaN,NaN
3,CD,5,nummod,4,61,B-DATE,1,4,61,0,...,wsj_0001.tsv,O,0,0,.,.,0,NaN,NaN,NaN
4,NNS,6,obl:npmod,5,year,I-DATE,1,5,years,0,...,wsj_0001.tsv,O,0,0,.,.,0,NaN,NaN,NaN

In [190]:
# how far is the content from the start of the paragraph

In [187]:
def get_distance_c2sentstart(df, list_of_tuples): 
    for t in list_of_tuples: 
        s, c = t
        start, end = c
        
        # Get the distance from the start of the document to the content span.
        c_doc = df.iloc[start]['filename']
        index_doc_start = df[df.filename == c_doc].first_valid_index()
        
        for i in range(start,end+1):
            df.loc[i, 'distance_c2docstart'] = i - index_doc_start
            
        # Get the distance from the start of the sentence to the content span.
        file_df = df.loc[df["filename"] == c_doc] # Filter by filename to get the correct indices.
        
        c_sent = df.iloc[start]["sentence_number"]
        index_sent_start = file_df[df.sentence_number == c_sent].first_valid_index()
        
        for i in range(start,end+1):
            df.loc[i, 'distance_c2sentstart'] = i-index_sent_start

In [188]:
get_distance_c2sentstart(df, list_of_tuples)

C:\Users\Windows 10\anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app

In [189]:
df[["filename", "sentence_number", "sentence_token_number","doc_token_number","distance_c2sentstart", "distance_c2docstart"]][45:70]

,filename,sentence_number,sentence_token_number,doc_token_number,distance_c2sentstart,distance_c2docstart
45,wsj_0002.tsv,1,15,15,NaN,NaN
46,wsj_0002.tsv,1,16,16,NaN,NaN
47,wsj_0002.tsv,1,17,17,NaN,NaN
48,wsj_0002.tsv,1,18,18,NaN,NaN
49,wsj_0002.tsv,1,19,19,NaN,NaN
50,wsj_0002.tsv,1,20,20,NaN,NaN
51,wsj_0002.tsv,1,21,21,NaN,NaN
52,wsj_0002.tsv,1,22,22,NaN,NaN
53,wsj_0002.tsv,1,23,23,NaN,NaN
54,wsj_0002.tsv,1,24,24,NaN,NaN
55,wsj_0002.tsv,1,25,25,24.0,24.0
56,wsj_0002.tsv,1,26,26,25.0,25.0
57,wsj_0003.tsv,1,1,1,26.0,26.0
58,wsj_0003.tsv,1,2,2,27.0,27.0
59,wsj_0003.tsv,1,3,3,28.0,28.0
60,wsj_0003.tsv,1,4,4,29.0,29.0
61,wsj_0003.tsv,1,5,5,30.0,30.0
62,wsj_0003.tsv,1,6,6,31.0,31.0
63,wsj_0003.tsv,1,7,7,32.0,32.0
64,wsj_0003.tsv,1,8,8,33.0,33.0
65,wsj_0003.tsv,1,9,9,34.0,34.0
66,wsj_0003.tsv,1,10,10,NaN,NaN
67,wsj_0003.tsv,1,11,11,NaN,NaN
68,wsj_0003.tsv,1,12,12,NaN,NaN
69,wsj_0003.tsv,1,13,13,NaN,NaN

In [242]:
# Check whether S is in C

def check_s_in_c(df, list_of_tuples):
    for t in list_of_tuples: 
        s, c = t 
        s_start, s_end = s
        c_start, c_end = c 
        s_span = list(df.iloc[s_start:s_end+1]["lemma"])
        c_span = list(df.iloc[c_start:c_end+1]["lemma"])
        result = all(elem in s_span for elem in c_span)
        
        for i in range(c_start, c_end):
            df.loc[i, 's_in_c'] = result

In [243]:
check_s_in_c(df, list_of_tuples)

In [244]:
df[45:70]

,POS,dependency_head,dependency_label,doc_token_number,lemma,ne_info,sentence_number,sentence_token_number,token,cue_label,...,ancestor_is_cue,cue_in_window_of_5,distance_to_prev_cue,distance_to_next_cue,cue_in_sentence,c_length,s_length,distance_c2sentstart,distance_c2docstart,s_in_c
45,",",17,punct,15,",",O,1,15,",",0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
46,VBD,17,aux:pass,16,be,O,1,16,was,0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
47,VBN,0,root,17,name,O,1,17,named,0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
48,DT,20,det,18,a,O,1,18,a,0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
49,JJ,20,amod,19,nonexecutive,O,1,19,nonexecutive,0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
50,NN,17,xcomp,20,director,O,1,20,director,0,...,0,0,.,.,0,NaN,4.0,NaN,NaN,False
51,IN,25,case,21,of,O,1,21,of,0,...,0,0,.,.,0,NaN,4.0,NaN,NaN,False
52,DT,25,det,22,this,O,1,22,this,0,...,0,0,.,.,0,NaN,4.0,NaN,NaN,False
53,JJ,25,amod,23,british,S-NORP,1,23,British,0,...,0,0,.,.,0,NaN,4.0,NaN,NaN,NaN
54,JJ,25,amod,24,industrial,O,1,24,industrial,0,...,0,0,.,.,0,NaN,NaN,NaN,NaN,NaN
55,NN,20,nmod,25,conglomerate,O,1,25,conglomerate,0,...,0,0,.,.,0,11.0,NaN,24.0,24.0,False
56,.,17,punct,26,.,O,1,26,.,0,...,0,0,.,.,0,11.0,NaN,25.0,25.0,False
57,DT,2,det,1,a,O,1,1,A,0,...,1,0,.,34,1,11.0,NaN,26.0,26.0,False
58,NN,13,nsubj,2,form,O,1,2,form,0,...,1,0,.,33,1,11.0,NaN,27.0,27.0,False
59,IN,4,case,3,of,O,1,3,of,0,...,1,0,.,32,1,11.0,NaN,28.0,28.0,False
60,NN,2,nmod,4,asbesto,O,1,4,asbestos,0,...,1,0,.,31,1,11.0,NaN,29.0,29.0,False
61,RB,6,advmod,5,once,O,1,5,once,0,...,1,0,.,30,1,11.0,NaN,30.0,30.0,False
62,VBD,35,ccomp,6,use,O,1,6,used,0,...,1,0,.,29,1,11.0,NaN,31.0,31.0,False
63,TO,8,mark,7,to,O,1,7,to,0,...,1,0,.,28,1,11.0,NaN,32.0,32.0,False
64,VB,6,xcomp,8,make,O,1,8,make,0,...,1,0,.,27,1,11.0,NaN,33.0,33.0,False
65,NNP,11,compound,9,Kent,S-GPE,1,9,Kent,0,...,1,0,.,26,1,11.0,NaN,34.0,34.0,NaN
66,NN,11,compound,10,cigarette,O,1,10,cigarette,0,...,1,0,.,25,1,NaN,NaN,NaN,NaN,NaN
67,NNS,8,obj,11,filter,O,1,11,filters,0,...,1,0,.,24,1,NaN,NaN,NaN,NaN,NaN
68,VBZ,13,aux,12,have,O,1,12,has,0,...,1,0,.,23,1,NaN,NaN,NaN,NaN,NaN
69,VBN,6,xcomp,13,cause,O,1,13,caused,0,...,1,0,.,22,1,NaN,NaN,NaN,NaN,NaN

# are other speakers mentioned in it
I don't know how to make this work.